#!/bin/bash

python3 setup.py build_ext --inplace "$@"

echo "Cleanup:"
echo "   rm -rf $PWD/build  cyfolds.html  cyfolds.c"
echo -n "Run the remove? [yn] "
read yesno
if yesno == "y" || yesno == "Y"; then
    rm -rf build cyfolds.html cyfolds.c
fi

# This command also works.
#cythonize -a -i cyfolds.pyx

