#!/bin/bash

PYTHON3_COMMAND="env python3" # Replace with path if you don't have env program.

$PYTHON3_COMMAND setup.py build_ext --inplace "$@" || \
      { echo "Error attempting to run setup.py with Python."; exit 1; }

echo
echo "Cleanup unneeded files:"
echo "   rm -rf build  cyfolds.html  cyfolds.c"
echo -n "Run the remove (default is 'y')? [yn] "
read yesno
if [ "$yesno" != "n" ] && [ "$yesno" != "N" ]; then
    rm -rf build cyfolds.html cyfolds.c
fi

# This command also works.
#cythonize -a -i cyfolds.pyx

