#!/bin/bash

python3 setup.py build_ext --inplace "$@" || exit 1

echo
echo "Cleanup unneeded files:"
echo "   rm -rf build  cyfolds.html  cyfolds.c"
echo -n "Run the remove (default is 'y')? [yn] "
read yesno
if [ "$yesno" != "n" ] && [ "$yesno" != "N" ]; then
    rm -rf build cyfolds.html cyfolds.c
fi

# This command also works.
#cythonize -a -i cyfolds.pyx

